#!/usr/bin/env bash
# Cloud Agent start phase: per-boot runtime initialization.
# Starts local PostgreSQL, ensures the app role/database exist, writes a
# local .env.local, and syncs + seeds the schema. Idempotent and safe to
# re-run on every boot.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

PG_VERSION="$(ls /etc/postgresql 2>/dev/null | sort -V | tail -1 || echo 16)"
DB_NAME="atlas"
DB_USER="atlas"
DB_PASS="atlas"

# --- Start PostgreSQL (idempotent) ---
if ! sudo pg_ctlcluster "$PG_VERSION" main status >/dev/null 2>&1; then
  echo "[start] Starting PostgreSQL cluster $PG_VERSION/main..."
  sudo pg_ctlcluster "$PG_VERSION" main start
fi

# Wait for the server to accept connections.
for _ in $(seq 1 30); do
  if sudo -u postgres pg_isready -q; then break; fi
  sleep 1
done

# --- Ensure role + database exist (idempotent) ---
sudo -u postgres psql -v ON_ERROR_STOP=1 <<SQL
DO \$\$ BEGIN
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname='${DB_USER}') THEN
    CREATE ROLE ${DB_USER} LOGIN PASSWORD '${DB_PASS}' SUPERUSER;
  END IF;
END \$\$;
SQL
if ! sudo -u postgres psql -tAc "SELECT 1 FROM pg_database WHERE datname='${DB_NAME}'" | grep -q 1; then
  sudo -u postgres createdb -O "${DB_USER}" "${DB_NAME}"
fi

# --- Write .env.local (picks up injected Supabase secrets when present) ---
DB_URL="postgresql://${DB_USER}:${DB_PASS}@127.0.0.1:5432/${DB_NAME}?schema=public"
cat > .env.local <<EOF
# Auto-generated by .cursor/start.sh for local Cloud Agent development.
DATABASE_URL="${DB_URL}"
DIRECT_URL="${DB_URL}"
NEXT_PUBLIC_SUPABASE_URL="${NEXT_PUBLIC_SUPABASE_URL:-https://placeholder.supabase.co}"
NEXT_PUBLIC_SUPABASE_ANON_KEY="${NEXT_PUBLIC_SUPABASE_ANON_KEY:-placeholder-anon-key}"
SUPABASE_SERVICE_ROLE_KEY="${SUPABASE_SERVICE_ROLE_KEY:-placeholder-service-role-key}"
PORTAL_SESSION_SECRET="${PORTAL_SESSION_SECRET:-local-dev-portal-session-secret-please-change-1234567890}"
CREW_API_KEY="${CREW_API_KEY:-local-dev-crew-api-key-read-only-1234567890}"
NEXT_PUBLIC_SITE_URL="${NEXT_PUBLIC_SITE_URL:-http://localhost:3005}"
NEXT_PUBLIC_APP_URL="${NEXT_PUBLIC_APP_URL:-http://localhost:3005}"
EOF

# --- Sync schema + seed reference data (idempotent) ---
echo "[start] Syncing Prisma schema..."
npm run db:push
echo "[start] Seeding reference data..."
npm run db:seed

echo "[start] Ready. Run 'npm run dev' (or use the dev terminal) to serve on http://localhost:3005"
