#!/usr/bin/env bash
# Cloud Agent start phase: per-boot runtime initialization.
#
# Two modes, chosen automatically from DATABASE_URL:
#   LOCAL  (default): no DATABASE_URL, or it points at localhost/127.0.0.1.
#                     Starts a local PostgreSQL, ensures the app role/db, then
#                     runs `prisma db push` + seed against that throwaway DB.
#   REMOTE (managed): DATABASE_URL points at a non-local host (e.g. Supabase
#                     staging). Uses that DB as-is and NEVER runs destructive
#                     `db push --accept-data-loss` or seed against it. Schema on
#                     managed DBs is owned by migrations, not this script.
#
# Idempotent and safe to re-run on every boot.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

LOCAL_DB_NAME="atlas"
LOCAL_DB_USER="atlas"
LOCAL_DB_PASS="atlas"
LOCAL_DB_URL="postgresql://${LOCAL_DB_USER}:${LOCAL_DB_PASS}@127.0.0.1:5432/${LOCAL_DB_NAME}?schema=public"

# Decide mode from the injected DATABASE_URL (if any).
INJECTED_DB_URL="${DATABASE_URL:-}"
DB_MODE="local"
if [ -n "$INJECTED_DB_URL" ] && ! printf '%s' "$INJECTED_DB_URL" | grep -qiE '@(127\.0\.0\.1|localhost)(:|/)'; then
  DB_MODE="remote"
fi

if [ "$DB_MODE" = "remote" ]; then
  echo "[start] REMOTE database detected — using injected DATABASE_URL as-is."
  echo "[start] Skipping local PostgreSQL, 'prisma db push', and seed to protect managed data."
  EFFECTIVE_DB_URL="$INJECTED_DB_URL"
  EFFECTIVE_DIRECT_URL="${DIRECT_URL:-$INJECTED_DB_URL}"
else
  echo "[start] LOCAL database mode."
  PG_VERSION="$(ls /etc/postgresql 2>/dev/null | sort -V | tail -1 || echo 16)"

  # --- Start PostgreSQL (idempotent) ---
  if ! sudo pg_ctlcluster "$PG_VERSION" main status >/dev/null 2>&1; then
    echo "[start] Starting PostgreSQL cluster $PG_VERSION/main..."
    sudo pg_ctlcluster "$PG_VERSION" main start
  fi

  # Wait for the server to accept connections.
  for _ in $(seq 1 30); do
    if sudo -u postgres pg_isready -q; then break; fi
    sleep 1
  done

  # --- Ensure role + database exist (idempotent) ---
  sudo -u postgres psql -v ON_ERROR_STOP=1 <<SQL
DO \$\$ BEGIN
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname='${LOCAL_DB_USER}') THEN
    CREATE ROLE ${LOCAL_DB_USER} LOGIN PASSWORD '${LOCAL_DB_PASS}' SUPERUSER;
  END IF;
END \$\$;
SQL
  if ! sudo -u postgres psql -tAc "SELECT 1 FROM pg_database WHERE datname='${LOCAL_DB_NAME}'" | grep -q 1; then
    sudo -u postgres createdb -O "${LOCAL_DB_USER}" "${LOCAL_DB_NAME}"
  fi

  EFFECTIVE_DB_URL="$LOCAL_DB_URL"
  EFFECTIVE_DIRECT_URL="$LOCAL_DB_URL"
fi

# --- Write .env.local (picks up injected Supabase secrets when present) ---
cat > .env.local <<EOF
# Auto-generated by .cursor/start.sh (${DB_MODE} database mode).
DATABASE_URL="${EFFECTIVE_DB_URL}"
DIRECT_URL="${EFFECTIVE_DIRECT_URL}"
NEXT_PUBLIC_SUPABASE_URL="${NEXT_PUBLIC_SUPABASE_URL:-https://placeholder.supabase.co}"
NEXT_PUBLIC_SUPABASE_ANON_KEY="${NEXT_PUBLIC_SUPABASE_ANON_KEY:-placeholder-anon-key}"
SUPABASE_SERVICE_ROLE_KEY="${SUPABASE_SERVICE_ROLE_KEY:-placeholder-service-role-key}"
PORTAL_SESSION_SECRET="${PORTAL_SESSION_SECRET:-local-dev-portal-session-secret-please-change-1234567890}"
CREW_API_KEY="${CREW_API_KEY:-local-dev-crew-api-key-read-only-1234567890}"
NEXT_PUBLIC_SITE_URL="${NEXT_PUBLIC_SITE_URL:-http://localhost:3005}"
NEXT_PUBLIC_APP_URL="${NEXT_PUBLIC_APP_URL:-http://localhost:3005}"
EOF

if [ "$DB_MODE" = "local" ]; then
  # Local throwaway DB only: safe to sync schema + seed reference data.
  echo "[start] Syncing Prisma schema (local)..."
  npm run db:push
  echo "[start] Seeding reference data (local)..."
  npm run db:seed
else
  echo "[start] Remote DB: verifying connectivity (read-only)..."
  npx prisma migrate status || true
fi

echo "[start] Ready (${DB_MODE} DB). Run 'npm run dev' (or use the dev terminal) to serve on http://localhost:3005"
